### ISSUE TITLE
Use a single job instead of two

### ISSUE THREAD

**Issue by cer** [eventuate-tram/eventuate-tram-core-quarkus#10]
@dartartem  It's inefficient to use two jobs instead of one job that can invoke both scripts.

```
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test-all
      - deploy-artifacts:
          context:
            - publish
          requires:
            - build-and-test-all
```
